### ISSUE TITLE
ElectrumX bitcoin support ? Other altcoins ?

### ISSUE THREAD

**Issue by iangregsondev** [spesmilo/electrumx#13]
Hi,

I am a little confused and wondered if anybody can confirm something?

I found this repo stating it was a fork of the original electrumx which seems to have dropped support for bitcoin (according to this readme) - although checking their repo it states they are dropping altcoin support and only bitcoin sv will be supported. So bitcoin (BTC) is still supported ?

Does this repo support BTC and does it support any altcoins ? I was looking specifically for litecoin.

Any help really appreciated.

Thanks

**Comment by JustinTArthur** [comment]
Yep, the original repo (kyuupichan/electrumx) now only supports Bitcoin SV. This fork (spesmilo/electrumx) focuses on Bitcoin and support for Electrum. This repo still has the altcoins, but you should know a few things:
* Our cryptocurrency focus remains on Bitcoin, and we don't provide support for working with other cryptocurrencies on the spesmilo GitHub organization repos, the Electrum subreddit, or the #electrum IRC channel.
* The altcoins are still supported in this repo's codebase while it's convenient, thanks to community-supplied code and unit tests.
* Should altcoin code get in the way of features for the Bitcoin protocol, the Lightning network, or Electrum wallet software, it will likely be removed rather than us spending time working around it.

If you want a wallet stratum daemon that focuses on Litecoin, you may want to consider doing what we did and fork the codebase and give it this sole focus. I'd suggest calling it something without the word Electrum if you do, just to avoid confusion.

**Comment by iangregsondev** [comment]
Thanks
